Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "Home"

urlpatterns = [
    
    
    path('', views.Homepage.as_view() , name = "home"), 
    path('home/', views.Homepage.as_view(), name = "home"),
    path('', views.Homepage.as_view() , name = "home"),
    path("profileaccount/", views.ReferralPageView.as_view(), name = "refferal-page"),
    path("afterclickin/", views.welcomeafterClickin.as_view(), name = "afterclickin"),
    path('payment/', views.view_paypal, name = 'payment'),
    path('payment-done/', views.payment_done, name= 'payment-done'),
    path('payment-cancelled/', views.payment_canceled, name = 'payment-cancelled'),
    path('withdraw/', views.WithdrawalView.as_view(), name = 'withdraw'),
    path('paypal_withdraw/', views.PaypalWithdrawalView.as_view(), name = 'paypal_withdraw'),
    path('validate_withdrawal/', views.validate_widthrawal, name = 'validate_withdrawal'),
    path('validate_paypal_withdrawal/', views.validate_Paypal_widthrawal, name = 'validate_paypal_withdrawal'),
    path('example/', views.example, name="example")
]

MpesaApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "MpesaApp"

urlpatterns = [
     
    path("lnm_payment/", views.view_for_mpesa, name = "mpesa_payment"),
    path('validate_payment/', views.lnm_validate_post, name = 'validate_payment'),
    path('validate_stk_code/', views.validate_mpesa_code, name = 'validate_mpesa_code'),
    path('lnm/', views.LNMCallbackUrl.as_view(), name = 'lnm-callbackurl'), 
    path('c2b_callback/', views.C2bCallbackUrl.as_view(), name = 'c2b-callbackurl'),
    path('b2c_callback/', views.B2cCallbackUrl.as_view(), name = 'b2c-callbackurl'),
]

Home/models.py
from django.db import models
from pinax.referrals.models import Referral
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    referral = models.OneToOneField(Referral,on_delete=models.CASCADE,primary_key=True,)
    referrer = models.CharField(max_length = 50, default = "None")
    referred = models.IntegerField(default = 0)
    paid = models.BooleanField(default = False)
    referrals_paid = models.IntegerField(default = 0)
    amount = models.IntegerField(default = 0)

    # referral_response = models.OneToOneField(Referral,on_delete=models.CASCADE, null= True,  related_name = "response_for_referral")


class WithdrawPayouts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    first_name= models.CharField(max_length = 20,)
    last_name = models.CharField(max_length = 20,blank = True, null = True)
    phone_number = models.CharField(max_length = 15,blank = True, null = True)
    email = models.CharField(max_length = 50)
    amount_request = models.FloatField(default = 0.0)
    amount_dispensed = models.FloatField(default= 0.0)
    referrals = models.IntegerField(default = 0,)
    date = models.DateTimeField(auto_now_add = True, blank = True, null = True )
    payment_mode = models.CharField(max_length = 20,blank = True, null = True)
    status = models.BooleanField(default= False)
    

Home/forms.py
from django import forms
from django.forms import ModelForm



class Mpesa_withwraw(forms.Form):
    
    first_name = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" Enter your first name  "}))
    
    last_name = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Enter your last name  "}))

    phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Enter a registered phone bumber  "}))
    
    email = forms.CharField(widget = forms.TextInput(attrs = {
        "placeholder": "Enter a valid email adress"
    }))

class Paypal_withdraw(forms.Form):
    
    f_name = forms.CharField(label = "First Name", widget = forms.TextInput(attrs = {
    'placeholder':" Enter your first name  "}))
    
    l_name = forms.CharField( label = "Last Name",widget = forms.TextInput(attrs = {
    'placeholder':"Enter your last name  "}))

    p_number = forms.CharField( label = "Phone Number",widget = forms.TextInput(attrs = {
    'placeholder':"Enter your phone bumber  "}))
    
    p_email = forms.CharField(label = "Paypal Email",widget = forms.TextInput(attrs = {
        "placeholder": "Enter paypal email adress"
    }))

    # class Meta:
        
    #     labels = {
    #         "l_name": "Last_name",
    #         "f_name" : "first_name",
    #         "p_number": "phone_number",
    #         "p_email": "paypal_email"
    #     }
        

MpesaApp/forms.py
from django import forms
from django.forms import ModelForm
# from .models import 


class Mpesa_checkout(forms.Form):
    
     phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"2547xxxxxxxxx  "}))
    
class Mpesa_c2b_checkout(forms.Form):

    mpesa_code = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" i.e MNxxxxx "}))





    

Home/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from . models  import Profile,WithdrawPayouts
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from pinax.referrals.models import Referral,ReferralResponse

### mpesa imports 
from .forms import Mpesa_withwraw,Paypal_withdraw
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from divineVentures.mpesa.LipaNaMpesa import lipa_na_mpesa
from django.http import JsonResponse
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
# from .serializers import LNMOnlineSerializer,C2bSerializer
from paypal.standard.forms import PayPalPaymentsForm


# Create your views here.

def example(request):
    
    return render(request, 'sucess.html' ,{})

class Homepage(generic.ListView):
    
    model = Profile
    template_name = "homepage_view.html"


class ReferralPageView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = "account_view.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(ReferralPageView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        referral_code = Profile.objects.get(user = self.request.user)

        referrer_qs = ReferralResponse.objects.filter( user = self.request.user ).first()

        if referrer_qs:


            referrer_confirmed =  Profile.objects.get( referral = referrer_qs.referral)
            print(referrer_confirmed.user)

            referrer = referrer_confirmed.user
            # qs =Referral.objects.get(user = self.request.user, label = "SIGNED_UP" )
            
            
        else:
            referrer = "None"
        qr = ReferralResponse.objects.filter(referral=referral_code.referral, action ="SIGNED_UP"  ).count()
        print(qr, "signed up")

        paid = ReferralResponse.objects.filter(referral=referral_code.referral, action ="PAID"  ).count()

        clicks = ReferralResponse.objects.filter(referral=referral_code.referral, action ="RESPONDED"  ).count()

        not_paid_referrals = paid - referral_code.referrals_paid
        amount = 3 * not_paid_referrals
        print(amount, "pay account balance")

        status_check = referral_code.paid 
        if status_check == True:
            status = "Paid"
        else:
            status = "Not Paid"

        referral_code.amount = amount
        referral_code.referrer = str(referrer)
        referral_code.referred = paid
        referral_code.save()
        # update to profile
        context["balance"] = amount
        context['paid'] = paid
        context["status"] = status
        context["referrer"] = referrer
        context["qr"] = qr
        context["clicks"] = clicks
        context['referral_code'] = referral_code

        return context

class welcomeafterClickin(generic.ListView):
    model = Profile
    template_name = "welcomeforclickers.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(welcomeafterClickin, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        referral = ReferralResponse.objects.filter( session_key = self.request.session.session_key  ).first()
        print(referral.referral)

        referral_code = Profile.objects.get(referral = referral.referral)
        print(referral_code.user)

        context['referrer'] = referral_code.user

        return context
  

@csrf_exempt
def payment_done(request):
    
    return render(request, 'payment_done.html' ,{})


@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment_cancelled.html')


def view_paypal(request):
    
    order = Profile.objects.filter(user = request.user,  paid = False)

    if order:
        print(order.user_id, "this is the cool order number")
        host = request.get_host()
        
        # What you want the button to do.
        paypal_dict = {
            "business": "misikovictor123@gmail.com",
            "amount": "5",
            "item_name":'Order for  {}'.format(order.user),
            "invoice": str(order.user_id),
            "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
            "return": request.build_absolute_uri(reverse('Home:payment-done')),
            "cancel_return": request.build_absolute_uri(reverse('Home:payment-cancelled')),
            "custom": request.user,  # Custom command to correlate to some function later (optional)
        }

        # Create the instance.
        form = PayPalPaymentsForm(initial=paypal_dict)
        context = {"form": form,
                    "order":  order
        }

        
        return render(request, "payment.html", context)


    else:
        return render(request, 'alreadypaid.html' ,{})

class WithdrawalView(generic.ListView):
    model = Profile
    template_name = "withdraw.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        referral_code = Profile.objects.get(user = self.request.user)
        payouts = WithdrawPayouts.objects.filter(user = self.request.user).order_by("-date")
        # print(len(payout), "payout history")
        context = super(WithdrawalView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        form = Mpesa_withwraw()
        form2 = Paypal_withdraw() 
        
        
                
        context = {"form": form,
                    "form2": form2,
                    "amount": referral_code.amount,
                    "referral_code": referral_code,
                    "payouts": payouts
                }
    

        return context

def validate_widthrawal(request):
    data = {}  
    profile = Profile.objects.get(user = request.user)
    
    
    form = Mpesa_withwraw(request.POST or None)
    if form.is_valid():
        
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        phone_number = form.cleaned_data.get("phone_number")
        email = form.cleaned_data.get("email")
        amount = profile.amount
        last = profile.referrals_paid
        current = profile.referred - profile.referrals_paid

        dp = 1 + 0.01*int(amount)
        amount_dispensed = amount - dp

        payout = WithdrawPayouts(
            user = request.user,
            first_name = first_name,
            last_name= last_name,
            phone_number= phone_number,
            email = email,
            amount_request = amount,
            amount_dispensed = amount_dispensed,
            referrals = current ,
            payment_mode= "Mpesa"
        )

        payout.save()
        profile.referrals_paid = last + current
        profile.amount = 0
        profile.save()

        span = 0.01*int(amount)
        data["percentage"] = "2"
        data['span'] = span
        data['gross'] = amount
        data["tcharges"]= dp
        data["net"] = amount_dispensed

        print(span, amount, dp, amount_dispensed, "this ire they")
       
        # messages.warning(request, " The form is not valid ")
        data["message"] =  "Withdrawal successful, your money is pending awaiting release"
        return JsonResponse(data)
    else:

        data["message"] =  "Not successful, form not valid"
        return JsonResponse(data)

def validate_Paypal_widthrawal(request):
    data = {}  
    profile = Profile.objects.get(user = request.user)
    
    
    form = Mpesa_withwraw(request.POST or None)
    if form.is_valid():
        
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        phone_number = form.cleaned_data.get("phone_number")
        email = form.cleaned_data.get("email")
        amount = profile.amount
        last = profile.referrals_paid
        current = profile.referred - profile.referrals_paid



        dp = 1 + 0.02*int(amount)
        amount_dispensed = amount - dp

        payout = WithdrawPayouts(
            user = request.user,
            first_name = first_name,
            last_name= last_name,
            phone_number= phone_number,
            email = email,
            amount_request = amount,
            amount_dispensed = amount_dispensed,
            referrals = current ,
            payment_mode= "Paypal"
        )
        payout.save()

        profile.referrals_paid = last + current
        profile.amount = 0
        profile.save()

        span = 0.02*int(amount)

        data["percentage"] = "2"
        data['span'] = span
        data['gross'] = amount
        data["tcharges"]= dp
        data["net"] = amount_dispensed
        
        # messages.warning(request, " The form is not valid ")
        data["message"] =  "Withdrawal successful, your money is pending awaiting release"
        return JsonResponse(data)
    else:

        data["message"] =  "Not successful, form not valid"
        return JsonResponse(data)

    
class PaypalWithdrawalView(generic.ListView):
    model = Profile
    template_name = "paypal_withdrawal.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        referral_code = Profile.objects.get(user = self.request.user)
        payouts = WithdrawPayouts.objects.filter(user = self.request.user).order_by("-date")
        # print(len(payout), "payout history")
        context = super(PaypalWithdrawalView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        form2 = Mpesa_withwraw()
        form = Paypal_withdraw()
        
        
                
        context = {"form": form,

Home/templates/alreadypaid.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% extends "base.html"%}
{% load  staticfiles %}

  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{%static 'css/mdb.min.css'%}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{%static 'css/style.min.css' %}" rel="stylesheet">


  </head>
  <body>
        {% block content %}

        <div style = "margin:auto" class = "card">
        <h1 class="card-title pt-5  mt-5 mx-5 text-center">   Payment Info </h1>
        

          <hr class="">
          <div class = "d-flex mx-auto justify-content-center">
              
                <li class=" text-center">
                    <i class="fas fa-check-circle fa-5x" style="color:rgb(17, 245, 9)" ></i>  Payment Already done
              
                   
                </li>
                      

          </div>
          <div class= "text-center">
              <P class = "pt-3 px-3"> Thank you for working with Divine Ventures, {{request.user}}. We wish to inform you that you had already paid your 
                  one time subscription fee, and there is no need for any further payment. 
              </P>
              <p>
                regards, 
              </p>
              <p>
                DivineVentures!  
              </P>

                  <hr class="mb-4"> 
                
              
          </div>
           
           <hr class="mb-4">

      </div>
        {% endblock%}
        {% block scripts%}
        {% endblock %}

  </body>
</html>

Home/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  
  <title> Divine Ventures  </title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{%                      static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css'%}" rel="stylesheet">
  <style type="text/css">
    /* Necessary for full page carousel*/

    html,
    body,
    header,
    .view {
      height: 100%;
    }

    /* Carousel*/
    .carousel,
    .carousel-item,
    .carousel-item.active {
      height: 400px;
    }
    .carousel-inner {
      height: 400px;
    }

    @media (min-width: 800px) and (max-width: 850px) {
      .navbar:not(.top-nav-collapse) {
          background: #1C2331!important;
      }
  }

/* *Preloader css* */

/* #loading{
    background-color: #ffcb0f;
    height: 100%;
    width: 100%;
    position: fixed;
    z-index: 1;
    margin-top: 0px;
    top: 0px;
    z-index: 90;
}
#loading-center{
    width: 100%;
    height: 100%;
    position: relative;
}
#loading-center-absolute {
    position: absolute;
    left: 50%;
    top: 50%;
    height: 50px;
    width: 150px;
    margin-top: -25px;
    margin-left: -75px;
}
.object{
    width: 8px;
    height: 50px;
    margin-right:5px;
    background-color: #FFF;
    -webkit-animation: animate 1s infinite;
    animation: animate 1s infinite;
    float: left;
}

.object:last-child {
    margin-right: 0px;
}

.object:nth-child(10){
    -webkit-animation-delay: 0.9s;
    animation-delay: 0.9s;	
}
.object:nth-child(9){
    -webkit-animation-delay: 0.8s;
    animation-delay: 0.8s;	
}	
.object:nth-child(8){
    -webkit-animation-delay: 0.7s;
    animation-delay: 0.7s;	
}
.object:nth-child(7){
    -webkit-animation-delay: 0.6s;
    animation-delay: 0.6s;	
}
.object:nth-child(6){
    -webkit-animation-delay: 0.5s;
    animation-delay: 0.5s;	
}
.object:nth-child(5){
    -webkit-animation-delay: 0.4s;
    animation-delay: 0.4s;
}
.object:nth-child(4){
    -webkit-animation-delay: 0.3s;
    animation-delay: 0.3s;		
}
.object:nth-child(3){
    -webkit-animation-delay: 0.2s;
    animation-delay: 0.2s;	
}
.object:nth-child(2){
    -webkit-animation-delay: 0.1s;
    animation-delay: 0.1s;
}						

@-webkit-keyframes animate {

    50% {
        -ms-transform: translateX(-25px) scaleY(0.5); 
        -webkit-transform: translateX(-25px) scaleY(0.5);
        transform: translateX(-25px) scaleY(0.5);

    }

}

@keyframes animate {
    50% {
        -ms-transform: translateX(-25px) scaleY(0.5); 
        -webkit-transform: translateX(-25px) scaleY(0.5);
        transform: translateX(-25px) scaleY(0.5);
    }

} */

/*End off Preloader*/
  </style>
</head>

<body>
  <!-- Preloader -->

  <!-- <div id="loading">
    <div id="loading-center">
        <div id="loading-center-absolute">
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
            <div class="object"></div>
        </div>
    </div>
</div> -->

<!--End off Preloader -->

    {% include "nav.html" %}

  
    {% block content %}

    {% endblock%}

  <!--Footer-->
  
  {% include "footer.html" %}

  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  {% block scripts %}
  
  <script  src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script  src="{% static 'js/bootstrap.bundle.js' %}"></script>
  <script  src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script  src="{% static 'js/bootstrap.min.js' %}"></script>

  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
<script>
$(window).load(function () {
        $("#loading").fadeOut(500);
    });

 </script>
  {% endblock %}
</body>

</html>

Home/templates/payment_cancelled.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% extends "base.html"%}
{% load  staticfiles %}

  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{%static "css/bootstrap.min.css"%}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{%static "css/mdb.min.css"%}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{%static "css/style.min.css" %}rel="stylesheet">

    

  </head>
  <body>
        {% block content %}
        <h1 class=" pt-5 pb-5 mt-5 mx-5">   payment Cancelled </h1>
        {% endblock%}
        {% block scripts%}
    {% endblock %}
  </body>
</html>

Home/templates/paypal_withdrawal.html
<html>
    {% extends "base.html" %}
    {%  load crispy_forms_tags %}
    {% load staticfiles %}
    <head>

        <title> withrawal </title>
        <style type="text/css"> 
          
        </style>
        
    </head>
<body>

       
              

        {% block content %}

        <Section class="pt-5 my-5 section1 ">
        
           <div class="container ">
                <h2 class="text-center text-success">Withdraw Cash </h2>
            <div class="card">
                <div class="card-header">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
                            aria-selected="true"><i class="fab fa-paypal"></i> Paypal</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
                            aria-selected="false">Mpesa</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
                            aria-selected="false">Contact</a>
                        </li>
                      </ul>
                </div>
                      <div class="tab-content card-body" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            
                          <div class="modal-body">

                            {% if referral_code.paid != True %}

                              <div class="alert alert-danger" role="alert">
                                  <P> Sorry, you have not subcribed to start earning from your referrals  </P>
                                  <P> You have {{referral_code.referred}} paid referrals</P>
                                  <p> If you wish to Claim your cash, please subscribe by paying $5 to access your cash</p>
                                  <p>Use the below <a href="{% url 'Home:mpesa_payment'%}"> link </a>  to pay for your subscription </p>
                                  <P> Goodluck !!</P>

                                </div>

                            {%  elif referral_code.amount >= 1 %}

                            <img class="mx-auto" src="{% static 'img/paypal1.jpg' %}" alt="" height= "70"> 
                           
                            <form id="post-paypal" class="">
                              <P>Request to withdraw <strong><span class="badge badge-pill blue z-depth-1 mr-1 ">${{ amount }} </span></strong></P>
                                {% csrf_token %}

                                {{ form|crispy }}
                                
                               
                               <button class="btn btn-primary " type="submit">Submit</button>
                            </form>

                            {% else %}
                            <div class="alert alert-danger" role="alert">
                                <P> Sorry, you do not have a enough credit to withdraw  </P>
                                <P> A minimum amount for withdraw  is $30 </P>
                                <p> Ensure you Get aleast 10 paid refferals to withdraw</p>
                                <P> Goodluck !!</P>

                              </div>
                            {% endif %}
                             </div>                           
                          </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            
                        </div>
                        
                      </div>
            </div>

            </div> 
            
        </Section>

        <!-- load progress  -->
        <section>
            <div class="container mb-5">
              <div style = "display: none" class="card load_progress">

                <div class="card-body">
                    <div  class = " text-center">
                        <h3 class="mr-3"> loading .... </h3>
                      
                        <hr class="my-2">
                        <img src = "{% static 'img/preloader.gif' %}"  height="200" width="150" >
        
                        
        
                      
                    </div>
                </div>

              </div>
            </div>
        </section>
        <!-- /load progress  -->

         <!-- successful transactioan  -->
        <section style = "display: none; " class="section2">
          <div class="container">
          <div  class=" card mx-auto mt-5">


              <div  class = "card-body mx-auto ">

                  <hr class="mb-5">
                  <div class = "row  wOW fadeIn">
                      <div class = " col-4 text-center  ">
                          <i class="fas fa-check-circle fa-5x" style="color:rgba(55, 0, 255, 0.911);" ></i>
                      </div>
                      <div class = " col-8 text-center  ">
                          <h5 class="mr-3 pt-4" style= "color:rgba(55, 0, 255, 0.911);">Request Succesful </h5>      
                      </div>
    
                  </div>
                  <div class= "text-center">
                      <P class = "pt-3 px-3">  Your withdrawal request has been sent, awaiting approval and release.</P>
                        <P> It takes less than 24 hours to be approved in a normal business day. </P>
    
                          <hr class="mb-4"> 
                        <a onClick="window.location.reload()" class = "btn btn-primary btn-rounded"> Refresh for status update </a>
                      
                  </div>
                   
                   <hr class="mb-4">
    
              </div>
              
          </div>
          <hr class="mb-4">
          </div>
        </section>
        <!--/ sucessful transactioan  -->

        <!-- transaction history  -->
        <section>
          <div id= "contact" class="container"> 
              <div class="card ">
                <div class="card-header">
                    <h2 class=" blue-text"> Transaction History </h2>

                </div>

                <div class=" card-body table-responsive text-nowrap">

                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">User</th>
                          <th scope="col">Payment Mode</th>
                          <th scope="col">Amount</th>
                          <th scope="col">Date</th>
                          <th scope="col">Status</th>
                          
                        </tr>
                      </thead>

                  

                      <tbody>
                        
                    {% for payout in payouts %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ payout.user}}</td>
                          <td>{{ payout.payment_mode}}</td>
                          <td>$ {{ payout.amount_request}}</td>
                          <td>{{ payout.date }}</td>
                          {%if payout.status == False %}
                          <td><span class="badge badge-pill purple " style="font-size: medium;"> pending ... </span></td>
                          {% else %}
                          <td><span class="badge badge-pill badge-success " style="font-size: medium;"> paid </span></td>
                          
                          {% endif %}
                        </tr>
                    {%  empty %}
                        <tr>
                          <td colspan="6"> You have no previous Transctions </td>
                        </tr>
                      
                    {% endfor %}
                      
                      </tbody>
                    </table>
                  
                </div>
              </div>
              <hr class="mb-5">
          </div>
        </section>
{% endblock %}

{% block scripts%}

<script>
  $('#post-paypal').on('submit', function(event){
   event.preventDefault();
   $(".load_progress").show();
   $(".section1").hide();
   // alert("hey submit is working")
   var first_name = $("#id_first_name").val();
   var last_name = $("#id_last_name").val();
   var phone_number = $("#id_phone_number").val();
   var email = $("#id_paypal_email").val();
  
   $.ajax({
     url: "{% url 'Home:validate_paypal_withdrawal' %}", 
     
     type:"POST" , 
     async: true,
     data: {
       "first_name": first_name,
       "last_name" : last_name,
       "phone_number" : phone_number,
       "email" : email,
       "csrfmiddlewaretoken": '{{ csrf_token }}' 
       },
     
     dataType: 'json',
     success: function (data) {
       alert(data.message); 
       $(".load_progress").hide();
       $(".section2").show();
         },
     failure:function (data) {
       alert(data.message) ;
       $(".section2").hide(); 
       $(".section1").show();    
         },

   });

 }); 
</script> 
  
{% endblock %} 

</body>  

</html>