Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "Home"

urlpatterns = [
    
    
    path('', views.Homepage.as_view() , name = "home"), 
    path('home/', views.Homepage.as_view(), name = "home"),
    path('', views.Homepage.as_view() , name = "home"),
    path("profileaccount/", views.ReferralPageView.as_view(), name = "refferal-page"),
    path("afterclickin/", views.welcomeafterClickin.as_view(), name = "afterclickin"),
    path('payment/', views.view_paypal, name = 'payment'),
    path('payment-done/', views.payment_done, name= 'payment-done'),
    path('payment-cancelled/', views.payment_canceled, name = 'payment-cancelled'),
    path('withdraw/', views.WithdrawalView.as_view(), name = 'withdraw'),
    path('paypal_withdraw/', views.PaypalWithdrawalView.as_view(), name = 'paypal_withdraw'),
    path('validate_withdrawal/', views.validate_widthrawal, name = 'validate_withdrawal'),
    path('validate_paypal_withdrawal/', views.validate_Paypal_widthrawal, name = 'validate_paypal_withdrawal'),
    path('example/', views.example, name="example")
]

MpesaApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "MpesaApp"

urlpatterns = [
     
    path("lnm_payment/", views.view_for_mpesa, name = "mpesa_payment"),
    path('validate_payment/', views.lnm_validate_post, name = 'validate_payment'),
    path('validate_stk_code/', views.validate_mpesa_code, name = 'validate_mpesa_code'),
    path('lnm/', views.LNMCallbackUrl.as_view(), name = 'lnm-callbackurl'), 
    path('c2b_callback/', views.C2bCallbackUrl.as_view(), name = 'c2b-callbackurl'),
    path('b2c_callback/', views.B2cCallbackUrl.as_view(), name = 'b2c-callbackurl'),
]

Home/models.py
from django.db import models
from pinax.referrals.models import Referral
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    referral = models.OneToOneField(Referral,on_delete=models.CASCADE,primary_key=True,)
    referrer = models.CharField(max_length = 50, default = "None")
    referred = models.IntegerField(default = 0)
    paid = models.BooleanField(default = False)
    referrals_paid = models.IntegerField(default = 0)
    amount = models.IntegerField(default = 0)

    # referral_response = models.OneToOneField(Referral,on_delete=models.CASCADE, null= True,  related_name = "response_for_referral")


class WithdrawPayouts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    first_name= models.CharField(max_length = 20,)
    last_name = models.CharField(max_length = 20,blank = True, null = True)
    phone_number = models.CharField(max_length = 15,blank = True, null = True)
    email = models.CharField(max_length = 50)
    amount_request = models.FloatField(default = 0.0)
    amount_dispensed = models.FloatField(default= 0.0)
    referrals = models.IntegerField(default = 0,)
    date = models.DateTimeField(auto_now_add = True, blank = True, null = True )
    payment_mode = models.CharField(max_length = 20,blank = True, null = True)
    status = models.BooleanField(default= False)
    

Home/forms.py
from django import forms
from django.forms import ModelForm



class Mpesa_withwraw(forms.Form):
    
    first_name = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" Enter your first name  "}))
    
    last_name = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Enter your last name  "}))

    phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"Enter a registered phone bumber  "}))
    
    email = forms.CharField(widget = forms.TextInput(attrs = {
        "placeholder": "Enter a valid email adress"
    }))

class Paypal_withdraw(forms.Form):
    
    f_name = forms.CharField(label = "First Name", widget = forms.TextInput(attrs = {
    'placeholder':" Enter your first name  "}))
    
    l_name = forms.CharField( label = "Last Name",widget = forms.TextInput(attrs = {
    'placeholder':"Enter your last name  "}))

    p_number = forms.CharField( label = "Phone Number",widget = forms.TextInput(attrs = {
    'placeholder':"Enter your phone bumber  "}))
    
    p_email = forms.CharField(label = "Paypal Email",widget = forms.TextInput(attrs = {
        "placeholder": "Enter paypal email adress"
    }))

    # class Meta:
        
    #     labels = {
    #         "l_name": "Last_name",
    #         "f_name" : "first_name",
    #         "p_number": "phone_number",
    #         "p_email": "paypal_email"
    #     }
        

MpesaApp/forms.py
from django import forms
from django.forms import ModelForm
# from .models import 


class Mpesa_checkout(forms.Form):
    
     phone_number = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':"2547xxxxxxxxx  "}))
    
class Mpesa_c2b_checkout(forms.Form):

    mpesa_code = forms.CharField( widget = forms.TextInput(attrs = {
    'placeholder':" i.e MNxxxxx "}))





    

Home/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from . models  import Profile,WithdrawPayouts
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from pinax.referrals.models import Referral,ReferralResponse

### mpesa imports 
from .forms import Mpesa_withwraw,Paypal_withdraw
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from divineVentures.mpesa.LipaNaMpesa import lipa_na_mpesa
from django.http import JsonResponse
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
# from .serializers import LNMOnlineSerializer,C2bSerializer
from paypal.standard.forms import PayPalPaymentsForm


# Create your views here.

def example(request):
    
    return render(request, 'sucess.html' ,{})

class Homepage(generic.ListView):
    
    model = Profile
    template_name = "homepage_view.html"


class ReferralPageView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = "account_view.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(ReferralPageView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        referral_code = Profile.objects.get(user = self.request.user)

        referrer_qs = ReferralResponse.objects.filter( user = self.request.user ).first()

        if referrer_qs:


            referrer_confirmed =  Profile.objects.get( referral = referrer_qs.referral)
            print(referrer_confirmed.user)

            referrer = referrer_confirmed.user
            # qs =Referral.objects.get(user = self.request.user, label = "SIGNED_UP" )
            
            
        else:
            referrer = "None"
        qr = ReferralResponse.objects.filter(referral=referral_code.referral, action ="SIGNED_UP"  ).count()
        print(qr, "signed up")

        paid = ReferralResponse.objects.filter(referral=referral_code.referral, action ="PAID"  ).count()

        clicks = ReferralResponse.objects.filter(referral=referral_code.referral, action ="RESPONDED"  ).count()

        not_paid_referrals = paid - referral_code.referrals_paid
        amount = 3 * not_paid_referrals
        print(amount, "pay account balance")

        status_check = referral_code.paid 
        if status_check == True:
            status = "Paid"
        else:
            status = "Not Paid"

        referral_code.amount = amount
        referral_code.referrer = str(referrer)
        referral_code.referred = paid
        referral_code.save()
        # update to profile
        context["balance"] = amount
        context['paid'] = paid
        context["status"] = status
        context["referrer"] = referrer
        context["qr"] = qr
        context["clicks"] = clicks
        context['referral_code'] = referral_code

        return context

class welcomeafterClickin(generic.ListView):
    model = Profile
    template_name = "welcomeforclickers.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(welcomeafterClickin, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        referral = ReferralResponse.objects.filter( session_key = self.request.session.session_key  ).first()
        print(referral.referral)

        referral_code = Profile.objects.get(referral = referral.referral)
        print(referral_code.user)

        context['referrer'] = referral_code.user

        return context
  

@csrf_exempt
def payment_done(request):
    
    return render(request, 'payment_done.html' ,{})


@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment_cancelled.html')


def view_paypal(request):
    
    order = Profile.objects.filter(user = request.user,  paid = False)

    if order:
        print(order.user_id, "this is the cool order number")
        host = request.get_host()
        
        # What you want the button to do.
        paypal_dict = {
            "business": "misikovictor123@gmail.com",
            "amount": "5",
            "item_name":'Order for  {}'.format(order.user),
            "invoice": str(order.user_id),
            "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
            "return": request.build_absolute_uri(reverse('Home:payment-done')),
            "cancel_return": request.build_absolute_uri(reverse('Home:payment-cancelled')),
            "custom": request.user,  # Custom command to correlate to some function later (optional)
        }

        # Create the instance.
        form = PayPalPaymentsForm(initial=paypal_dict)
        context = {"form": form,
                    "order":  order
        }

        
        return render(request, "payment.html", context)


    else:
        return render(request, 'alreadypaid.html' ,{})

class WithdrawalView(generic.ListView):
    model = Profile
    template_name = "withdraw.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        referral_code = Profile.objects.get(user = self.request.user)
        payouts = WithdrawPayouts.objects.filter(user = self.request.user).order_by("-date")
        # print(len(payout), "payout history")
        context = super(WithdrawalView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        form = Mpesa_withwraw()
        form2 = Paypal_withdraw() 
        
        
                
        context = {"form": form,
                    "form2": form2,
                    "amount": referral_code.amount,
                    "referral_code": referral_code,
                    "payouts": payouts
                }
    

        return context

def validate_widthrawal(request):
    data = {}  
    profile = Profile.objects.get(user = request.user)
    
    
    form = Mpesa_withwraw(request.POST or None)
    if form.is_valid():
        
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        phone_number = form.cleaned_data.get("phone_number")
        email = form.cleaned_data.get("email")
        amount = profile.amount
        last = profile.referrals_paid
        current = profile.referred - profile.referrals_paid

        dp = 1 + 0.01*int(amount)
        amount_dispensed = amount - dp

        payout = WithdrawPayouts(
            user = request.user,
            first_name = first_name,
            last_name= last_name,
            phone_number= phone_number,
            email = email,
            amount_request = amount,
            amount_dispensed = amount_dispensed,
            referrals = current ,
            payment_mode= "Mpesa"
        )

        payout.save()
        profile.referrals_paid = last + current
        profile.amount = 0
        profile.save()

        span = 0.01*int(amount)
        data["percentage"] = "2"
        data['span'] = span
        data['gross'] = amount
        data["tcharges"]= dp
        data["net"] = amount_dispensed

        print(span, amount, dp, amount_dispensed, "this ire they")
       
        # messages.warning(request, " The form is not valid ")
        data["message"] =  "Withdrawal successful, your money is pending awaiting release"
        return JsonResponse(data)
    else:

        data["message"] =  "Not successful, form not valid"
        return JsonResponse(data)

def validate_Paypal_widthrawal(request):
    data = {}  
    profile = Profile.objects.get(user = request.user)
    
    
    form = Mpesa_withwraw(request.POST or None)
    if form.is_valid():
        
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        phone_number = form.cleaned_data.get("phone_number")
        email = form.cleaned_data.get("email")
        amount = profile.amount
        last = profile.referrals_paid
        current = profile.referred - profile.referrals_paid



        dp = 1 + 0.02*int(amount)
        amount_dispensed = amount - dp

        payout = WithdrawPayouts(
            user = request.user,
            first_name = first_name,
            last_name= last_name,
            phone_number= phone_number,
            email = email,
            amount_request = amount,
            amount_dispensed = amount_dispensed,
            referrals = current ,
            payment_mode= "Paypal"
        )
        payout.save()

        profile.referrals_paid = last + current
        profile.amount = 0
        profile.save()

        span = 0.02*int(amount)

        data["percentage"] = "2"
        data['span'] = span
        data['gross'] = amount
        data["tcharges"]= dp
        data["net"] = amount_dispensed
        
        # messages.warning(request, " The form is not valid ")
        data["message"] =  "Withdrawal successful, your money is pending awaiting release"
        return JsonResponse(data)
    else:

        data["message"] =  "Not successful, form not valid"
        return JsonResponse(data)

    
class PaypalWithdrawalView(generic.ListView):
    model = Profile
    template_name = "paypal_withdrawal.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        referral_code = Profile.objects.get(user = self.request.user)
        payouts = WithdrawPayouts.objects.filter(user = self.request.user).order_by("-date")
        # print(len(payout), "payout history")
        context = super(PaypalWithdrawalView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        form2 = Mpesa_withwraw()
        form = Paypal_withdraw()
        
        
                
        context = {"form": form,

Home/templates/mpesatemp/payment_via_mpesa.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html"%}
{%  load crispy_forms_tags %}
{% load  staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title></title>
  
  <style type="text/css"> -->
    html,
    body,
    main,
    .load_progress {
      display: none;
      text-align: center;
      
    }
  </style>
  
  
</head>
  
  
<body class="grey lighten-3">

{% block content %}
  <!-- Navbar -->

  <!--Main layout-->
  <main >
    <div id= "id_top" class="container wow fadeIn pt-5">

      <!-- Heading -->
      <h1 class="my-5 h2 text-center">Pay with Mpesa</h1>
      

      
      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div  class="col-md-8 mb-4">
          <h2 class ="green-text "> Lipa na M<a style = 'color:red;'><i class="fas fa-mobile-alt"></i></a>pesa</h2>

          <!--Card-->
          <div class="card mb-3">

            <h4 class="card-title blue-text col-md-12 text-center pt-4"><strong>Payment Option 0ne</strong></h4>

            <div style = "display: none;  margin:auto" class = "load_progress card-body text-center">
                <h3 class="mr-3"> Please Wait .... </h3>
               
                <hr class="my-2">
                <img src = "{% static 'img/preloader.gif' %}"  style="width: 100px; height: 70px;" ></img>

                <hr class="my-2">
                <p> Enter Your PIN once Prompted !! </p>

                <hr class="my-2">

            </div>
            <!-- stk -mpesa code  -->
            <form  method= "POST"  id = "post-code" class=" mpesa_code card-body text-center">
                {% csrf_token %}

                <div style = "display: none;  margin:auto" class = " md-form mpesa_code text-center">
                    <p class = " blue-text"> succesful stk-push!! </p>

                  <h3 class="mr-3 "> Enter your Mpesa Transaction Code </h3>
              
        

                  <input type="text" id="id_mpesa_code" class="form-control" placeholder=" Mpesa code ">

                  <hr class="mb-4">
                <button  class= " btn btn-info "  type = "submit">submit</button>
                
                <hr class="mb-4">
                <P>Not yet paid? <a href="" id="id_back" >Back</a></P>
              </div>
            </form>
           <!-- stk -- mpesa code  -->
            
           <!-- paid  -->
           <div style = "display: none;  margin:auto" class = "payment_successful">

              <hr class="mb-5">
              <div class = "row  wOW fadeIn">
                  <div class = " col-4 text-center  ">
                      <i class="fas fa-check-circle fa-5x" style="color:rgba(55, 0, 255, 0.911);" ></i>
                  </div>
                  <div class = " col-8 text-center  ">
                      <h5 class="mr-3 pt-4" style= "color:rgba(55, 0, 255, 0.911);">Payment Succesful </h5>      
                  </div>

              </div>
              <div class= "text-center">
                  <P class = "pt-3 px-3"> Thank you for working with Divine Ventures. A world of Opportunities is 
                    awaiting you {{ request.user }}. You can now start earning from your referrals infinetly without 
                    paying a single dime, from now hence fourth.
                  </P>
                  <p>
                    regards, 
                  </p>
                  <p>
                    DivineVentures!  
                  </P>

                      <hr class="mb-4"> 
                    
                  
              </div>
               
               <hr class="mb-4">

          </div>
           <!-- paid   -->

           <!--Card content-->
          <div class="load-hide card-body text-center">
                
                <!-- Text -->
            <p class="card-text">Enter your M-Pesa phone number below and Click  <strong>Pay now </strong> then check your 
              phone handset for an instant payment prompt from safaricom M-pesa.
              </p>
           
            <form method= "POST"  id = "post-form" class="card-body">
                {% csrf_token %}

                <p class = "card-text"> Enter a registered Phone number in the right format  </p>
                <p class = "card-text red-text">  format e.g -> 2547xxxxxxxx </p>
               
  
                <!--address-->
                <div class="col-12  md-form mb-5">
                   
                  <!-- <input type="text" id="address" class="form-control" placeholder=" "> -->
  
                  {{ form.phone_number }}

                  
                </div>

                <hr class="mb-4">
                <button  class= " btn btn-info "  type = "submit">Pay Now</button>
                <P>Already paid? <a href="#" class="confirm_code"  onclick="return false;" >Enter your mpesa code </a></P>
              </form>
                
            </div>
          </div>

           <!--Card-->
           <div class="load-hide card">

              <h4 class="card-title blue-text text-center pt-4"><strong>payment Option Two</strong></h4>
  
              <div class="card-body text-center">
                  <!--Card content-->
                  <!-- Text -->
              <p class="card-text">Send  <strong>KSH:{{ order.get_total }} </strong> to paybill number <strong>5672543 </strong> and Account number
                 <strong>0721649416</strong>. Once you recieve the confirmation message on your phone, click refresh button to view your status.
                </p>

                <div class="view view-cascade overlay">
                  
                  <h2><a style= "color:rgba(55, 0, 255, 0.911);">
                      <i class="fas fa-sync-alt">Refresh</i>
                  </a></h2>
                </div>
                  
              <form method= "POST" class="card-body"
                  <p class = "card-text"> If the invoice status still indicates UNPAID, enter below your confirmation code  </p>
                 
                  {% csrf_token %}
    
                  <!--address-->
                  <div class="col-12  md-form mb-5">
                      <label for="address" class="pb-5"> * confimation code </label>
                    <!-- <input type="text" id="address" class="form-control" placeholder=" "> -->
    
                    {{ form2.mpesa_code}}
  
                    
                  </div>
  
                  <hr class="mb-4">
                  <button class= " btn btn-info " type="submit">Pay Now</button>
    
                </form>
                  
              </div>
            </div>

        </div>
          
          <!--/.Card-->
      <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">subscription Fee</h6>
                <small class="text-muted">Start earning by paying </small>
              </div>
              <span class="text-muted">Ksh: 500 </span>
            </li>
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.item.title }}</h6>
                <small class="text-muted">{{ order_item.item.description }} </small>
              </div>
              <span class="text-muted">Ksh: {{ order_item.get_final_price }} </span>
            </li>
            {% endfor %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$0.0</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (Ksh.)</span>
              <strong> 500/=</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>






  {% endblock %}

  {% block scripts %}

  
  
<script>
  $('#post-form').on('submit', function(event){
    event.preventDefault();
    $(".load_progress").show();
    $(".load-hide").hide();
    window.phone_number = $("#id_phone_number").val();
    
    $.ajax({
      url: "{% url 'MpesaApp:validate_payment' %}",
    
      async: true,
      data: {
        "phone_number": window.phone_number
        
        },
      
      dataType: 'json',
      success: function (data) {
        // alert(data.message) 

        $(".mpesa_code").show();
        $(document).scrollTop($('.mpesa_code').offset().top)     
          },
      error:function (data) {
        alert(data.err_message)      
          },

    });

  }); 

</script>

<script>

  $('#post-code').on('submit', function(event){
    event.preventDefault();
    // $(".load_progress").show();
    // console.log("what is happening")
    // alert("hey submit is working")
    var mpesa_code = $("#id_mpesa_code").val();
    
    $.ajax({
      url: "{% url 'MpesaApp:validate_mpesa_code' %}",
    
      async: true,
      data: {
        "mpesa_code": mpesa_code    
        },
      
      dataType: 'json',
      success: function (data) {
        alert(data.message) 
        if (data.message == "Transaction Successful") {
          $(".mpesa_code").hide();   
          $(".load_progress").hide();
          $(".payment_successful").show();
          $(".load-hide").hide();

          }
        else  
          {
            $(".mpesa_code").show();   
            $(".load_progress").show();
            }
          },
      failure:function (data) {
        alert(data.message)      
          },

    });

  }); 
</script>

<script>
  $('.confirm_code').click(function (event) {
      // alert("clicked")
      $(".load_progress").show();
      $(".mpesa_code").show();   
      
      $(".load-hide").hide();
      $(document).scrollTop($('.mpesa_code').offset().top)
});
</script>

<script>
  $('#id_back').click(function (event) {
      event.preventDefault();
      
      $(".load_progress").hide();
      $(".mpesa_code").hide();   
      
      $(".load-hide").show();
      $(document).scrollTop($('#id_top').offset().top)

});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script>
<script>
  //websockets
  loc =window.location
 //  console.log(loc)
  
 var wstart = "WSS://"
  //  if (loc.protocol == "https"){
  //    wstart = "wss://"
  //  }
  
  var endpoint = wstart + loc.host + loc.pathname
  var socket = new ReconnectingWebSocket(endpoint)

  socket.onmessage = function(e){
    console.log("message" ,e);
    var message = JSON.parse(e.data)
    var phone_number = $('#id_phone_number').val()
    // var audio = new Audio("{% static 'when.mp3'%}")
    if ( message.phone_number == window.phone_number){
      $(".mpesa_code").hide();   
      $(".load_progress").hide();
      $(".payment_successful").show();
      $(".load-hide").hide();
      console.log(window.phone_number);
      console.log("{{request.user}}");
      var finalData = {
        "user": "{{request.user}}",
        "request": "{{request}}" 
      }
      socket.send(JSON.stringify(finalData));
     }
    // else{
    //   alert(" payment not from you ");
    //   console.log(window.phone_number);
    // }


   }
  socket.onopen = function(e){
    console.log("open" ,e);
   
   
  }
  socket.onerror=function(e){
    console.log("error" ,e)
  }
  socket.onclose =function(e){
    console.log("close" ,e)
  }

 </script> 
 
  {% endblock %}


</body>

</html>